overrides:
  install:
    extra_packages:
      deb:
        - gcc
        - libc6-dev
      rpm:
        - gcc
        - glibc-devel
  ceph:
    conf:
      mgr:
        debug client: 10

tasks:
  - cephfs_test_runner:
      modules:
        - tasks.cephfs.test_mirroring.TestMirroring
